// bake-env.cjs — bake env.json (KayKit Medieval Hexagon, CC0) into the game's
// environment atlases: assets/env/env.{alb,nrm,key}.png + env.json (per-sprite
// rect, origin, footprint), and src/sim/envfoot.js (footprints for collision —
// the sim never reads renderer assets). Needs `npm i` + `sh fetch-env.sh`.
const fs = require('fs'), path = require('path');
const { chromium } = require('playwright-core');
const { serve, CHROME, GL } = require('./render.cjs');
const DIR = __dirname, ROOT = path.join(DIR, '..', '..'), OUT = path.join(ROOT, 'assets', 'env');
(async () => {
  if (!fs.existsSync(path.join(DIR, 'models', 'env', 'building_home_A_red.gltf'))) throw new Error('models missing — run: sh fetch-env.sh');
  const list = JSON.parse(fs.readFileSync(path.join(DIR, 'env.json')));
  const srv = await serve(DIR), port = srv.address().port;
  const b = await chromium.launch({ executablePath: CHROME, args: GL });
  const p = await b.newPage(); p.on('pageerror', (e) => console.log('PAGEERR', e.message));
  await p.goto(`http://127.0.0.1:${port}/env.html`); await p.waitForFunction(() => window.ready === true, { timeout: 60000 });
  const t0 = Date.now(), r = await p.evaluate(async (l) => await window.bakeAll(l), list);
  fs.mkdirSync(OUT, { recursive: true });
  for (const c of ['alb', 'nrm', 'key']) fs.writeFileSync(path.join(OUT, `env.${c}.png`), Buffer.from(r[c].split(',')[1], 'base64'));
  fs.writeFileSync(path.join(OUT, 'env.json'), JSON.stringify({ width: r.width, height: r.height, sprites: r.meta }) + '\n');
  const foot = Object.fromEntries(Object.entries(r.meta).map(([k, m]) => [k, m.foot]));
  fs.writeFileSync(path.join(ROOT, 'src', 'sim', 'envfoot.js'),
    '// envfoot.js — GENERATED by tools/actor-lab/bake-env.cjs. Do not edit.\n' +
    '// Ground footprint of each baked environment sprite, in tiles relative to its\n// origin: [x0, y0, x1, y1]. Used for collision and placement.\n' +
    'export const ENV_FOOT = ' + JSON.stringify(foot) + ';\n');
  console.log(`baked ${list.length} sprites → ${r.width}×${r.height} atlases in ${((Date.now() - t0) / 1000).toFixed(1)}s`);
  await b.close(); srv.close();
})().catch((e) => { console.error('FAIL', e.message); process.exit(1); });
